name: Android Instrumented Tests

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [16, 23, 29]
        target: [default]
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedCheck
      env:
        TEST_KEY: ${{ secrets.TEST_KEY }}