name: Android Instrumented Tests

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [21, 23, 26, 29]
        target: [default]
        arch: [x86]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: ${{ matrix.arch }}
        profile: Nexus 6
        script: ./gradlew connectedCheck
      env:
        TEST_KEY: ${{ secrets.TEST_KEY }}